# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItD0R6Rg8RAhHxLNu551sLo8YQCEssCJ
"""

from FADS_NLP import batch_comments, extract_replies, extract_3plus_replies